### PR TITLE
Zugzwang detection enhancement

### PR DESCRIPTION
**Pull request by pb00068**
LTC fixed num games:
http://tests.stockfishchess.org/tests/view/5bb3704a0ebc592439f6d7ef
ELO: 3.51 +-3.8 (95%) LOS: 96.3%
Total: 10000 W: 1642 L: 1541 D: 6817

LTC SPRT:
http://tests.stockfishchess.org/tests/view/5bb3d1240ebc592439f6dfee
LLR: -2.96 (-2.94,2.94) [0.00,5.00]
Total: 15599 W: 2456 L: 2518 D: 10625 
Elo	-0.94 [-4.11,2.32] (95%)

Solves some of the hardest zugzwang-problems

n1QBq1k1/5p1p/5KP1/p7/8/8/8/8 w - - 0 1 finds Bxc7 
n2Bqk2/5p1p/Q4KP1/p7/8/8/8/8 w - - finds Qc8 
n1QBq1k1/5p1p/5KP1/p6p/4p3/8/4P2P/8 w - - 0 1 finds Bxc7 
8/6pp/1K6/N5P1/3N4/8/npn1P3/k7 w - - 0 1 finds Nab3+ 

bench:  5543771

### CODE REVIEW

**Comment by ddugovic** [comment]
I wonder why this works and if there is a more generic solution.

**Comment by pb00068** [comment]
@ddugovic The patch is complex  and therefore cannot be explained by one sentence, but mainly the patch works because of 2 reasons:
- letting fail low (=fail high from rootpos view) the promising variation beyond  current's bestmove
`return Value(thisThread->rootMoves[0].score * (thisThread->rootPos.side_to_move() != us ? 1 : -1) - 80);`
makes this variant principal for the next iteration, so it will be analyzed much deeper than before where it was strongly lmr-reduced 
- since we already detected a mate when we get into the prospected position (7k/2n2P1p/5K2/p1q5/8/8/8/B7 b - - 6 5 prospected to 7k/2n2P1p/5K2/2q5/8/8/8/B7 b - - 0 9 ), it's now enough that the search reaches that specific position: even with depth 0, from the transposition table it will immediately understand that it's mate.

P.S.: I'm trying hard to find a more generic solution ... ;-)

**Comment by gonzalezjo** [comment]
Is there any reason this isn’t a PR to official-stockfish?

**Comment by ddugovic** [comment]
It seems to fail LTC SPRT, despite being useful for resolving zugzwang positions.

**Comment by pb00068** [comment]
@jhellis3 Hi Joseph, any interest in testing/merging this?

**Comment by jhellis3** [comment]
In its current form, not really.  I have tested a much more general & simpler implementation, but did not notice any significant improvement.   Of note, MF already solves the 4 posted positions in what I consider reasonable time.

**Comment by MichaelB7** [comment]
@pb00068 - Gunther , I have merged a few of your  patches over at the Stockfish/McCain fork - will update the source tonight.  Will send you a note when the fork is updated later today ( USA EDST time zone ) 8-10 hours from now. Would appreciate any suggestions you might have. Thx.

**Pull request closed without merging**
